---

interfaces: 
  - {name: swp1, addr: 10.3.3.0, mask: 31, peering_link: true}
  - {name: swp2, addr: 10.3.4.0, mask: 31, peering_link: true}
  - {name: swp51, addr: 10.10.30.1, mask: 31, peering_link: true}
  - {name: swp52, addr: 10.20.30.1, mask: 31, peering_link: true}
as: 30000
range: 3